name: Build React App for GitHub Pages
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  deploy:
    name: Deploy React App
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up git user
        uses: fregante/setup-git-user@v2
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - name: Set up yarn
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: Build bundle
        uses: borales/actions-yarn@v4
        with:
          cmd: build
      - name: Deploy to gh-pages branch
        uses: borales/actions-yarn@v4
        with:
          cmd: deploy
        
