# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Ryan Morrison
title: Software Developer, Backend
# email: notreal@example.com
website: https://ryanmorrison.net

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: ryanmorrison04
github_username:  rmmorrison
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
facebook_username: ryan.morrison
# flickr_username: jekyll
instagram_username: ryan.morrison04
linkedin_username: ryanmorrison04
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi there! I'm Ryan, and I'm a software developer focused on backend systems. I have years of experience building high-performance Java-based backend web applications, delivering to some of the largest names in the telecom industry worldwide. I'm a strong team player with leadership skill under my belt.

  Some of my hands-on skills include: <mark>Java 8+</mark>, the <mark>Spring</mark> Framework (and Spring Boot!), <mark>Docker</mark>, <mark>Kubernetes</mark>, <mark>Hazelcast</mark> and <mark>Eating Pizza</mark>.

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Amdocs Media
        link: amdocs.com
        sub_title: Senior Software Developer
        caption: February 2018 - Present
        description: | # this will include new lines to allow paragraphs
            _UXP Systems, Inc. was acquired by Amdocs in February 2018._

            During my tenure in this role, I was a key contributor to the product's migration from a legacy monolith on-premise design to a microservice-based architecture delivered via a SaaS model. Some notable achievements during this time include:
            * Designed and delivered a complete multi-tenancy strategy including internal product changes and database re-structuring
            * Working in a technical/team lead role to guide a delivery team through a substantial product version upgrade
            * Assumed the role of a scrum master, managing JIRA boards and running scrum ceremony meetings
            * Coordinated requirements between project managers, solution architects and development teams
            * Provided routine status update reports to senior management
      - layout: left
        title: UXP Systems
        link: uxpsystems.com
        sub_title: Senior Software Developer
        caption: February 2017 - February 2018
        description: | # this will include new lines to allow paragraphs
            During my tenure in this role, I was a key contributor to the product's migration from a legacy monolith on-premise design to a microservice-based architecture delivered via a SaaS model. Some notable achievements during this time include:
            * Designed and delivered a complete multi-tenancy strategy including internal product changes and database re-structuring
            * Working in a technical/team lead role to guide a delivery team through a substantial product version upgrade
            * Assumed the role of a scrum master, managing JIRA boards and running scrum ceremony meetings
            * Coordinated requirements between project managers, solution architects and development teams
            * Provided routine status update reports to senior management
      - layout: left
        title: UXP Systems
        link: uxpsystems.com
        sub_title: Software Developer
        caption: April 2013 - February 2017
        description: | # this will include new lines to allow paragraphs
            During my tenure in this role, I was a key contributor to the product's migration from a legacy monolith on-premise design to a microservice-based architecture delivered via a SaaS model. Some notable achievements during this time include:
            * Designed and delivered a complete multi-tenancy strategy including internal product changes and database re-structuring
            * Working in a technical/team lead role to guide a delivery team through a substantial product version upgrade
            * Assumed the role of a scrum master, managing JIRA boards and running scrum ceremony meetings
            * Coordinated requirements between project managers, solution architects and development teams
            * Provided routine status update reports to senior management

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Sheridan College
        caption: 2009 - 2011
        sub_title: Diploma, Software Engineering (with Honours)

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
